# Chem 274B: Software Engineering Fundamentals for
#            Molecular Sciences 
# 
# Creator:  Tony Drummond, PhD.  Faculty
# Date Created: September 24, 2022
# Date Updated: September 22, 2023
#
# This makefile creates object files that are executable 
# They test the functionalities in Week7/Source/Datatypes
# After creating the executable files they are moved to 
# the ../Bin subdirectory

# Students need to write their make targets below
